// This icon file is generated by build/generateIcons.ts
// tslint:disable

import { IconDefinition } from '../types';

const ArrowsAltOutline: IconDefinition = {
  name: 'arrows-alt',
  theme: 'outline',
  icon: {
    tag: 'svg',
    attrs: { viewBox: '0 0 32 32' },
    children: [
      {
        tag: 'path',
        attrs: {
          d:
            'M12.81 18.19L1.31 29.75V22.7c0-.38-.25-.69-.62-.69s-.69.31-.69.69v8.62c0 .13 0 .2.06.25 0 .13.07.13.13.2v.05s.06 0 .06.07c.06 0 .13.06.19.06.06.06.12.06.25.06H9.3c.38 0 .7-.31.7-.69s-.32-.62-.7-.62H2.25l11.5-11.56c.31-.25.25-.7 0-.94s-.69-.25-.94 0zM32 .62c0-.06 0-.12-.06-.18 0-.13-.07-.2-.13-.25-.06-.07-.12-.13-.25-.13C31.5 0 31.44 0 31.31 0H22.7c-.38 0-.7.31-.7.69s.32.62.7.62h7.06L18.19 12.88a.68.68 0 0 0 0 .93c.12.13.31.2.43.2a.7.7 0 0 0 .5-.2L30.7 2.25v7.06c0 .38.25.7.62.7s.7-.32.7-.7V.7.62z'
        }
      }
    ]
  }
};

export default ArrowsAltOutline;
