// This icon file is generated by build/generateIcons.ts
// tslint:disable

import { IconDefinition } from '../types';

const BarChartOutline: IconDefinition = {
  name: 'bar-chart',
  theme: 'outline',
  icon: {
    tag: 'svg',
    attrs: { viewBox: '0 0 32 32' },
    children: [
      {
        tag: 'path',
        attrs: {
          d:
            'M29.31 2.69v26.69H2.63V2.68H29.3m1.32-1.3H1.3v29.3h29.32zm-12 12h-1.25V24h1.25zM13.38 12H12v12h1.38zM8 16H6.62v8H8zm16-8h-1.38v16H24z'
        }
      }
    ]
  }
};

export default BarChartOutline;
