// This icon file is generated by build/generateIcons.ts
// tslint:disable

import { IconDefinition } from '../types';

const CheckOutline: IconDefinition = {
  name: 'check',
  theme: 'outline',
  icon: {
    tag: 'svg',
    attrs: { viewBox: '0 0 32 32' },
    children: [
      {
        tag: 'path',
        attrs: {
          d:
            'M31.75.13c-.31-.2-.75-.13-.94.12L9.25 30.31 1.12 22.2c-.25-.25-.68-.25-.93 0s-.25.69 0 .94l8.68 8.68c.13.13.32.2.44.2h.07c.18 0 .37-.13.5-.26l22-30.69c.18-.3.12-.75-.13-.93z'
        }
      }
    ]
  }
};

export default CheckOutline;
