// This icon file is generated by build/generateIcons.ts
// tslint:disable

import { IconDefinition } from '../types';

const ClockOutline: IconDefinition = {
  name: 'clock',
  theme: 'outline',
  icon: {
    tag: 'svg',
    attrs: { viewBox: '0 0 32 32' },
    children: [
      {
        tag: 'path',
        attrs: {
          d:
            'M16 0C7.19 0 0 7.19 0 16s7.19 16 16 16c8.81 0 16-7.19 16-16S24.81 0 16 0zm0 30.69C7.94 30.69 1.31 24.06 1.31 16S7.94 1.31 16 1.31c8.06 0 14.69 6.63 14.69 14.69S24.06 30.69 16 30.69zm0-15v-7c0-.38-.31-.69-.69-.69s-.62.31-.62.69V16c0 .19.06.38.18.5l8 7.31c.13.13.32.2.44.2a.7.7 0 0 0 .5-.2c.25-.3.25-.75 0-1z'
        }
      }
    ]
  }
};

export default ClockOutline;
