// This icon file is generated by build/generateIcons.ts
// tslint:disable

import { IconDefinition } from '../types';

const DesktopOutline: IconDefinition = {
  name: 'desktop',
  theme: 'outline',
  icon: {
    tag: 'svg',
    attrs: { viewBox: '0 0 32 32' },
    children: [
      {
        tag: 'path',
        attrs: {
          d:
            'M29.31 1.31H2.7A2.74 2.74 0 0 0 0 4.13v19.75a2.74 2.74 0 0 0 2.69 2.8H15.3V28H6.7c-.38 0-.69.31-.69.69s.31.62.69.62H25.3c.38 0 .7-.25.7-.62s-.32-.69-.7-.69H16.7V26.7H29.3c1.5 0 2.7-1.25 2.7-2.81V4.13a2.74 2.74 0 0 0-2.7-2.82zM2.7 2.7H29.3c.75 0 1.38.62 1.38 1.44V20H1.3V4.13c0-.82.63-1.44 1.38-1.44zM29.3 25.3H2.7a1.4 1.4 0 0 1-1.38-1.43V21.3H30.7v2.57a1.4 1.4 0 0 1-1.38 1.43zm-12-2c0 .75-.56 1.38-1.31 1.38s-1.31-.63-1.31-1.38c0-.68.56-1.31 1.31-1.31s1.31.63 1.31 1.31z'
        }
      }
    ]
  }
};

export default DesktopOutline;
