// This icon file is generated by build/generateIcons.ts
// tslint:disable

import { IconDefinition } from '../types';

const DownloadOutline: IconDefinition = {
  name: 'download',
  theme: 'outline',
  icon: {
    tag: 'svg',
    attrs: { viewBox: '0 0 32 32' },
    children: [
      {
        tag: 'path',
        attrs: {
          d:
            'M15.5 25.13c.13.12.31.18.5.18s.38-.06.5-.18l9.31-9.32c.2-.19.25-.5.13-.75-.06-.25-.31-.37-.63-.37h-4v-14c0-.38-.25-.7-.62-.7H11.3c-.37 0-.62.32-.62.7v14h-4c-.31 0-.56.12-.63.37a.66.66 0 0 0 .13.75zM11.31 16a.7.7 0 0 0 .7-.69v-14h8v14c0 .19.05.38.18.5s.31.19.5.19h3.06L16 23.75 8.25 16zm20 8c-.37 0-.62.31-.62.69v6H1.3v-6c0-.38-.25-.69-.62-.69s-.69.31-.69.69v6.62c0 .38.31.7.69.7H31.3a.7.7 0 0 0 .7-.7V24.7a.7.7 0 0 0-.7-.69z'
        }
      }
    ]
  }
};

export default DownloadOutline;
