// This icon file is generated by build/generateIcons.ts
// tslint:disable

import { IconDefinition } from '../types';

const DownOutline: IconDefinition = {
  name: 'down',
  theme: 'outline',
  icon: {
    tag: 'svg',
    attrs: { viewBox: '0 0 32 32' },
    children: [
      {
        tag: 'path',
        attrs: { d: 'M15.94 23.75L1.13 8.94l1-.94 13.8 13.87L29.89 8l.93.94z' }
      }
    ]
  }
};

export default DownOutline;
