// This icon file is generated by build/generateIcons.ts
// tslint:disable

import { IconDefinition } from '../types';

const EditOutline: IconDefinition = {
  name: 'edit',
  theme: 'outline',
  icon: {
    tag: 'svg',
    attrs: { viewBox: '0 0 32 32' },
    children: [
      {
        tag: 'path',
        attrs: {
          d:
            'M24 15.31a.7.7 0 0 0-.69.7v14.68h-22V4h18c.38 0 .69-.31.69-.69s-.31-.62-.69-.62H0V32h24.69V16a.7.7 0 0 0-.7-.69zm7.88-14A2.16 2.16 0 0 0 29.93 0c-.5 0-1 .19-1.38.63L26.7 2.5 15.8 13.31c0 .07-.06.13-.12.2l-1.88 3.74c-.12.31-.06.63.13.81.12.13.31.2.5.2.06 0 .19 0 .31-.07l3.75-1.88c.06-.06.13-.12.19-.12L31.38 3.44c.62-.63.8-1.38.5-2.13zM17.8 15.12l-1.87.94.94-1.87L27.13 3.87l1 1zM30.44 2.5l-1.38 1.38-.93-.94 1.37-1.38a.54.54 0 0 1 .44-.25c.31 0 .56.25.69.5s.06.44-.2.69z'
        }
      }
    ]
  }
};

export default EditOutline;
