// This icon file is generated by build/generateIcons.ts
// tslint:disable

import { IconDefinition } from '../types';

const ExclamationCircleOutline: IconDefinition = {
  name: 'exclamation-circle',
  theme: 'outline',
  icon: {
    tag: 'svg',
    attrs: { viewBox: '0 0 32 32' },
    children: [
      {
        tag: 'path',
        attrs: {
          d:
            'M15.56 0h-.25A15.48 15.48 0 0 0 0 15.63a15.07 15.07 0 0 0 15.06 15.06h.32c4.06-.06 7.93-1.75 10.87-4.69s4.5-6.87 4.44-10.94C30.5 6.62 23.88 0 15.56 0zm9.75 25.06a14.43 14.43 0 0 1-10 4.25h-.25c-7.56 0-13.56-6-13.75-13.75C1.2 7.87 7.51 1.5 15.38 1.31h.18c7.63 0 13.63 6.07 13.75 13.75a13.92 13.92 0 0 1-4 10zm-10-7.06a.7.7 0 0 0 .7-.69V8c0-.38-.32-.69-.7-.69s-.62.31-.62.69v9.31c0 .38.25.69.62.69zm0 2.69c-.75 0-1.31.62-1.31 1.31 0 .75.63 1.31 1.31 1.31h.07c.68 0 1.3-.62 1.3-1.3a1.38 1.38 0 0 0-1.37-1.32z'
        }
      }
    ]
  }
};

export default ExclamationCircleOutline;
