// This icon file is generated by build/generateIcons.ts
// tslint:disable

import { IconDefinition } from '../types';

const FileOutline: IconDefinition = {
  name: 'file',
  theme: 'outline',
  icon: {
    tag: 'svg',
    attrs: { viewBox: '0 0 1024 1024' },
    children: [
      {
        tag: 'path',
        attrs: {
          d:
            'M812 84v856H172V366L452 84h360zM256 340h212V128L256 340zm512-212H512v256H212v512h556V128z'
        }
      }
    ]
  }
};

export default FileOutline;
