// This icon file is generated by build/generateIcons.ts
// tslint:disable

import { IconDefinition } from '../types';

const FileOutline: IconDefinition = {
  name: 'file',
  theme: 'outline',
  icon: {
    tag: 'svg',
    attrs: { viewBox: '0 0 32 32' },
    children: [
      {
        tag: 'path',
        attrs: {
          d:
            'M16 2.63h-1.88l-8.74 8.8v17.95h20V2.63zM14.62 4v6.63H8zM24 28H6.62V12H16V4h8z'
        }
      }
    ]
  }
};

export default FileOutline;
