// This icon file is generated by build/generateIcons.ts
// tslint:disable

import { IconDefinition } from '../types';

const FilterOutline: IconDefinition = {
  name: 'filter',
  theme: 'outline',
  icon: {
    tag: 'svg',
    attrs: { viewBox: '0 0 32 32' },
    children: [
      {
        tag: 'path',
        attrs: {
          d:
            'M4 2.63l9.38 14.75v10.75h5.24V17.38L28 2.63zm13.25 24.12h-2.5v-9.31h2.5zM17.88 16h-3.75L6.5 4h19z'
        }
      }
    ]
  }
};

export default FilterOutline;
