// This icon file is generated by build/generateIcons.ts
// tslint:disable

import { IconDefinition } from '../types';

const FolderOutline: IconDefinition = {
  name: 'folder',
  theme: 'outline',
  icon: {
    tag: 'svg',
    attrs: { viewBox: '0 0 32 32' },
    children: [
      {
        tag: 'path',
        attrs: {
          d:
            'M12.5 6.63l1 1.93.38.75h15.5v17.32H2.63V9.3l1.43.07h.82l.3-.75 1-2h6.32m.88-1.25h-8L4.05 8H2a.63.63 0 0 0-.63.63V27.3c0 .38.25.7.63.7h28c.37 0 .62-.32.62-.7V8.63A.63.63 0 0 0 30 8H14.62z'
        }
      }
    ]
  }
};

export default FolderOutline;
