// This icon file is generated by build/generateIcons.ts
// tslint:disable

import { IconDefinition } from '../types';

const HeartOutline: IconDefinition = {
  name: 'heart',
  theme: 'outline',
  icon: {
    tag: 'svg',
    attrs: { viewBox: '0 0 32 32' },
    children: [
      {
        tag: 'path',
        attrs: {
          d:
            'M23.94 2.19c-3 0-6.38 1.69-7.94 5.5a8.57 8.57 0 0 0-7.94-5.5C4.2 2.19 0 5 0 11.19c0 4.56 2.62 9.37 7.87 14.19 3.88 3.56 7.63 5.75 7.82 5.87.06.06.19.06.31.06s.25 0 .31-.06c.2-.12 3.94-2.31 7.82-5.87 5.25-4.82 7.87-9.63 7.87-14.2 0-6.18-4.19-9-8.06-9zM16 29.88c-2.19-1.38-14.69-9.44-14.69-18.7 0-5.24 3.5-7.68 6.75-7.68 3 0 6.38 2.06 7.31 6.62 0 .32.32.57.63.57s.63-.25.63-.57c.93-4.56 4.3-6.62 7.3-6.62 3.26 0 6.76 2.44 6.76 7.69 0 9.25-12.5 17.31-14.69 18.69z'
        }
      }
    ]
  }
};

export default HeartOutline;
