// This icon file is generated by build/generateIcons.ts
// tslint:disable

import { IconDefinition } from '../types';

const InfoCircleOutline: IconDefinition = {
  name: 'info-circle',
  theme: 'outline',
  icon: {
    tag: 'svg',
    attrs: { viewBox: '0 0 32 32' },
    children: [
      {
        tag: 'path',
        attrs: {
          d:
            'M15.31 0a15.34 15.34 0 1 0 .05 30.68A15.34 15.34 0 0 0 15.31 0zm0 29.31c-7.68 0-14-6.25-14-14 0-7.69 6.32-14 14-14 7.75 0 14 6.32 14 14 0 7.75-6.25 14-14 14zm4-5.31H16V12.69a.7.7 0 0 0-.69-.7H12.7c-.38 0-.7.32-.7.7s.32.62.7.62h2V24H11.3c-.37 0-.62.31-.62.69s.25.62.62.62h8c.38 0 .69-.25.69-.62s-.31-.69-.69-.69zM14 8c.75 0 1.31-.63 1.31-1.31 0-.75-.56-1.38-1.31-1.38s-1.31.63-1.31 1.38c0 .68.56 1.31 1.31 1.31zm0-1.31z'
        }
      }
    ]
  }
};

export default InfoCircleOutline;
