// This icon file is generated by build/generateIcons.ts
// tslint:disable

import { IconDefinition } from '../types';

const MailOutline: IconDefinition = {
  name: 'mail',
  theme: 'outline',
  icon: {
    tag: 'svg',
    attrs: { viewBox: '0 0 32 32' },
    children: [
      {
        tag: 'path',
        attrs: {
          d:
            'M27.31 6.69H6.7V4H10a.7.7 0 0 0 .69-.69V.7a.7.7 0 0 0-.69-.7H6a.7.7 0 0 0-.69.7v6H4.7A4.63 4.63 0 0 0 0 11.3v12c0 .38.31.69.69.69H17.3v7.31c0 .38.32.7.7.7s.68-.32.68-.7V24H31.3a.7.7 0 0 0 .7-.69v-12a4.63 4.63 0 0 0-4.7-4.62zM6.7 1.3H9.3V2.7H6.7zm-5.38 10a3.35 3.35 0 0 1 6.7 0V22.7H1.3zM30.7 22.7H9.3V11.3c0-1.31-.5-2.44-1.37-3.31H27.3c1.88 0 3.38 1.5 3.38 3.31zM6 20H3.31c-.37 0-.62.31-.62.69s.25.62.62.62H6c.38 0 .69-.25.69-.62S6.37 20 6 20z'
        }
      }
    ]
  }
};

export default MailOutline;
