// This icon file is generated by build/generateIcons.ts
// tslint:disable

import { IconDefinition } from '../types';

const PaperClipOutline: IconDefinition = {
  name: 'paper-clip',
  theme: 'outline',
  icon: {
    tag: 'svg',
    attrs: { viewBox: '0 0 32 32' },
    children: [
      {
        tag: 'path',
        attrs: {
          d:
            'M29.06 5.69a7.95 7.95 0 0 0-11.31 0l-16 16a6.07 6.07 0 0 0 0 8.5C2.94 31.3 4.44 31.94 6 31.94s3.06-.63 4.25-1.75L25.56 14.8a3.47 3.47 0 0 0 0-4.75c-.62-.62-1.5-.93-2.37-.93s-1.75.3-2.38.93L9.5 21.44c-.25.25-.25.69 0 .94s.69.25.94 0L21.8 11.06a1.93 1.93 0 0 1 2.82 0c.37.38.56.88.56 1.38 0 .56-.19 1.06-.56 1.44L9.3 29.25a4.71 4.71 0 0 1-6.62 0 4.71 4.71 0 0 1 0-6.62l16-16a6.66 6.66 0 0 1 4.75-1.94 6.64 6.64 0 0 1 4.69 11.38L16.8 27.36c-.25.26-.25.7 0 .95s.7.25.94 0L29.06 17a8 8 0 0 0 0-11.31z'
        }
      }
    ]
  }
};

export default PaperClipOutline;
