// This icon file is generated by build/generateIcons.ts
// tslint:disable

import { IconDefinition } from '../types';

const PictureOutline: IconDefinition = {
  name: 'picture',
  theme: 'outline',
  icon: {
    tag: 'svg',
    attrs: { viewBox: '0 0 32 32' },
    children: [
      {
        tag: 'path',
        attrs: {
          d:
            'M0 0v32h32V0zm30.69 1.31V22.7h-.94l-4.56-9.07A2.76 2.76 0 0 0 22.62 12c-1.06 0-2 .56-2.5 1.44l-3.56 6.06c-1-1.25-3.25-3.5-5.87-3.5-3.32 0-5.75 5.06-6.44 6.69H1.3V1.3zM28.25 22.7H5.69c1-2.07 2.94-5.38 5-5.38 2.94 0 5.37 3.7 5.44 3.75.12.2.3.25.56.25s.44-.12.56-.31l4-6.88c.31-.5.81-.8 1.38-.8s1.12.37 1.37.87zm-26.94 8V24H30.7v6.69zM8.7 12h4c2.19 0 4-1.81 4-4a4.03 4.03 0 0 0-7.81-1.31C7.38 6.56 6 7.8 6 9.3s1.19 2.7 2.69 2.7zm0-4c.12 0 .31.06.44.13l.8.24.13-.8A2.63 2.63 0 0 1 12.7 5.3c1.44 0 2.62 1.19 2.62 2.69s-1.18 2.69-2.62 2.69h-4c-.75 0-1.38-.63-1.38-1.38C7.31 8.63 7.94 8 8.7 8z'
        }
      }
    ]
  }
};

export default PictureOutline;
