// This icon file is generated by build/generateIcons.ts
// tslint:disable

import { IconDefinition } from '../types';

const PlusCircleOutline: IconDefinition = {
  name: 'plus-circle',
  theme: 'outline',
  icon: {
    tag: 'svg',
    attrs: { viewBox: '0 0 32 32' },
    children: [
      {
        tag: 'path',
        attrs: {
          d:
            'M15.31 0A15.34 15.34 0 0 0 0 15.31c0 4.07 1.56 7.94 4.5 10.82a14.98 14.98 0 0 0 10.81 4.56c8.44 0 15.32-6.88 15.38-15.31A15.4 15.4 0 0 0 15.3 0zm0 29.31c-7.75 0-14-6.31-14-14 .07-7.69 6.32-14 14.07-14 7.68.07 14 6.32 13.93 14.07 0 7.68-6.25 13.93-14 13.93zm8-14.62H16V7.3c0-.37-.31-.62-.69-.62s-.62.25-.62.62v7.38h-7.5c-.38 0-.63.25-.63.62s.25.7.63.7h7.5v7.3c0 .38.25.7.62.7s.69-.32.69-.7v-7.3h7.31c.38 0 .7-.32.7-.63a.7.7 0 0 0-.7-.7z'
        }
      }
    ]
  }
};

export default PlusCircleOutline;
