// This icon file is generated by build/generateIcons.ts
// tslint:disable

import { IconDefinition } from '../types';

const PushpinOutline: IconDefinition = {
  name: 'pushpin',
  theme: 'outline',
  icon: {
    tag: 'svg',
    attrs: { viewBox: '0 0 32 32' },
    children: [
      {
        tag: 'path',
        attrs: {
          d:
            'M31.81 9.5L22.5.19a.76.76 0 0 0-1 0l-2.63 2.68a.68.68 0 0 0 0 .94l.88.88-6 6H8.69a.7.7 0 0 0-.5.19l-2 2a.68.68 0 0 0 0 .93l5.56 5.5L.19 30.88a.68.68 0 0 0 0 .94c.12.12.31.18.5.18.12 0 .31-.06.43-.18L12.7 20.25l5.5 5.57c.12.12.31.18.5.18.12 0 .31-.06.44-.18l2-2a.71.71 0 0 0 .18-.5v-5.07l6-6 .88.88c.25.25.69.25.94 0l2.69-2.63a.76.76 0 0 0 0-1zm-3.12 2.25l-.88-.88a.68.68 0 0 0-.93 0l-6.7 6.63a.71.71 0 0 0-.18.5v5.06l-1.31 1.32L7.62 13.3 8.94 12H14a.7.7 0 0 0 .5-.19l6.62-6.69a.68.68 0 0 0 0-.93l-.87-.88L22 1.62 30.37 10z'
        }
      }
    ]
  }
};

export default PushpinOutline;
