// This icon file is generated by build/generateIcons.ts
// tslint:disable

import { IconDefinition } from '../types';

const ShrinkOutline: IconDefinition = {
  name: 'shrink',
  theme: 'outline',
  icon: {
    tag: 'svg',
    attrs: { viewBox: '0 0 32 32' },
    children: [
      {
        tag: 'path',
        attrs: {
          d:
            'M31.81.19a.68.68 0 0 0-.93 0l-12.2 12.19v-7.7c0-.37-.3-.68-.68-.68s-.69.31-.69.69v9.25c0 .06 0 .19.06.31.13.25.32.44.63.44h9.31c.38 0 .69-.31.69-.69s-.31-.69-.69-.69h-7.75L31.81 1.13a.68.68 0 0 0 0-.94zM14.63 17.75a.56.56 0 0 0-.38-.38c-.06 0-.19-.06-.25-.06H4.62c-.3 0-.62.32-.62.69s.31.69.63.69h7.75L.18 30.88a.68.68 0 0 0 0 .93c.13.13.32.2.5.2.13 0 .32-.07.44-.2l12.2-12.18v7.68c0 .38.3.7.68.7s.69-.32.69-.7v-9.3c0-.07-.06-.2-.06-.26z'
        }
      }
    ]
  }
};

export default ShrinkOutline;
