// This icon file is generated by build/generateIcons.ts
// tslint:disable

import { IconDefinition } from '../types';

const StarOutline: IconDefinition = {
  name: 'star',
  theme: 'outline',
  icon: {
    tag: 'svg',
    attrs: { viewBox: '0 0 32 32' },
    children: [
      {
        tag: 'path',
        attrs: {
          d:
            'M31.94 11.81a.6.6 0 0 0-.63-.5H20.5L16.62.44C16.57.19 16.32 0 16 0s-.56.19-.63.44L11.5 11.3H.69a.6.6 0 0 0-.63.5c-.12.25 0 .57.19.7l9 7.05-3.88 11.57c-.12.25 0 .56.25.75.2.19.57.19.75 0L16 24.8l9.63 7.07c.12.06.25.12.37.12s.25-.06.38-.12c.25-.2.37-.5.25-.75l-3.88-11.57 9-7.06c.25-.12.31-.44.19-.69zm-10.38 7c-.18.2-.31.44-.18.75l3.3 10-8.3-6.12c-.13-.07-.25-.13-.38-.13s-.25.07-.38.13l-8.3 6.12 3.3-10c.13-.31 0-.56-.18-.75L2.62 12.7H12c.31 0 .56-.19.62-.44L16 2.69l3.37 9.56c.07.25.32.44.63.44h9.37z'
        }
      }
    ]
  }
};

export default StarOutline;
