// This icon file is generated by build/generateIcons.ts
// tslint:disable

import { IconDefinition } from '../types';

const YoutubeOutline: IconDefinition = {
  name: 'youtube',
  theme: 'outline',
  icon: {
    tag: 'svg',
    attrs: { viewBox: '0 0 32 32' },
    children: [
      {
        tag: 'path',
        attrs: {
          d:
            'M31.31 6.69H.7c-.38 0-.69.25-.69.62v22.7c0 .37.31.68.69.68H31.3a.7.7 0 0 0 .7-.69V7.31c0-.37-.32-.62-.7-.62zm-10 20v2.62H10.7V26.7zm-20-1.38V12H30.7v13.31zM10.7 10.7V8H21.3v2.69zm20 0h-8V8h8zM1.3 8h8v2.69h-8zm0 18.69h8v2.62h-8zM30.7 29.3h-8V26.7h8zM20.25 18.06l-7.31-3.31c-.2-.13-.44-.13-.63 0s-.31.37-.31.56v6.7c0 .24.12.43.31.55.13.07.25.13.38.13.06 0 .19-.06.25-.06l7.31-3.38a.6.6 0 0 0 .44-.56c0-.32-.19-.5-.44-.63zm-6.94 2.88v-4.57l5.07 2.32z'
        }
      }
    ]
  }
};

export default YoutubeOutline;
